// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"lizzy/medium/compare/go-gin/persistence"
	"lizzy/medium/compare/go-gin/rest"
)

// Injectors from wire.go:

func InitializeEngine() (*gin.Engine, func()) {
	db, cleanup := persistence.NewDB()
	issueRepository := persistence.NewIssueRepository(db)
	issueController := rest.NewIssueController(issueRepository)
	engine := rest.NewEngine(issueController)
	return engine, func() {
		cleanup()
	}
}
