micronaut:
  application:
    name: micronaut-jdk
datasources:
  default:
    url: jdbc:postgresql://postgres:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES
