// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"lizzy/medium/compare/persistence"
	"lizzy/medium/compare/rest"
)

// Injectors from wire.go:

func InitializeEngine() (rest.Engine, func()) {
	db, cleanup := persistence.Connect()
	issueRepository := persistence.NewIssueRepository(db)
	issueController := rest.NewIssueController(issueRepository)
	engine := rest.NewEngine(issueController)
	return engine, func() {
		cleanup()
	}
}
