---
version: '3'
services:
  spring:
    build:
      context: ../spring/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  micronaut-jdk:
    build:
      context: ../micronaut-jdk/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  micronaut-graal:
    image: micronaut-graal:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  go:
    build:
      context: ../go/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  node-ts:
    build:
      context: ../node-ts/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  node-js:
    build:
      context: ../node-js/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  python-django:
    build:
      context: ../python-django/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  python-falcon:
    build:
      context: ../python-falcon/
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
